;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny202]
platform = atmelmegaavr
board = ATtiny202
framework = arduino
upload_protocol = serialupdi
build_src_filter =
  +<main.cpp>
  -<main_native.cpp>
  -<mock/*>
  -<test/*>

[env:native]
platform = native
test_framework = unity
build_src_filter =
  +<main_native.cpp>
  -<main.cpp>
  -<test/*>
  -<drivers/*>
  -<hal/*>
lib_deps =
  throwtheswitch/Unity@^2.6.1
